// Helpers for turning a YouTube URL into an embeddable video id / thumbnail.
// Supports the common URL shapes: watch?v=, youtu.be/, /embed/, /shorts/.

const YT_PATTERNS = [
  /[?&]v=([\w-]{11})/, // youtube.com/watch?v=ID
  /youtu\.be\/([\w-]{11})/, // youtu.be/ID
  /\/embed\/([\w-]{11})/, // youtube.com/embed/ID
  /\/shorts\/([\w-]{11})/, // youtube.com/shorts/ID
];

/** Extract the 11-char YouTube video id from a URL, or null if it isn't one. */
export function getYouTubeId(url: string | undefined): string | null {
  if (!url) return null;
  for (const re of YT_PATTERNS) {
    const m = url.match(re);
    if (m) return m[1];
  }
  return null;
}

/**
 * Thumbnail URL for a video id. `hqdefault` (480×360) is chosen because it is
 * always generated by YouTube — unlike `maxresdefault`, which 404s for many
 * videos and would leave a broken image.
 */
export function getYouTubeThumbnail(id: string): string {
  return `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
}

/** Privacy-friendly (nocookie) embed URL for a video id. */
export function getYouTubeEmbed(id: string): string {
  return `https://www.youtube-nocookie.com/embed/${id}`;
}
